version: '3.8'

services:
  api-gateway:
    build:
      context: .
    ports:
      - "8080:8080"
    env_file: .env # Loads variables from .env file first
    environment:
      # KEYCLOAK_REALM_NAME will be picked up from .env
      # Override .env variables for Docker Compose internal networking
      KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/${KEYCLOAK_REALM_NAME}
      REDIS_HOST: redis
      # REDIS_PORT will be taken from .env or default to 6379, which is fine
    depends_on:
      keycloak:
        condition: service_healthy # Wait for keycloak to be healthy
      redis:
        condition: service_healthy  # Wait for redis to be healthy
    networks:
      - fortexa-net

networks:
  fortexa-net:
    driver: bridge